universe = vanilla
Executable = run_EtaToMuMuGamma_2022MiniAOD.sh
should_transfer_files = YES
transfer_input_files = EtaToMuMuGamma_2022Test_DIGIRAWHLT_cfg.py
request_memory = 4000
+JobFlavour = "tomorrow"
Output = jobfiles/EtaMuMuGamma$(Cluster)_$(Process).out
Error = jobfiles/EtaMuMuGamma$(Cluster)_$(Process).err
Log = jobfiles/EtaMuMuGamma$(Cluster)_$(Process).log
Arguments = $ENV(USER) $(Process)
#Queue 700
#Queue 83
#Queue 4
#Queue 3500
#Queue 10500
#Queue 2000
Queue 1000
#Queue 1 
